### ISSUE TITLE
Can only enter one character.

### ISSUE THREAD

**Issue by sajidfrommerqata** [andrelandgraf/react-datalist-input#28]
Can only enter one character in the textbox when I try to enter the second character the textbox clears automatically. Can you let me know, is it an issue with the plugin or my configuration?

Code: https://prnt.sc/10ovbnt
UI: https://prnt.sc/10ov99e

Thank You in advance

**Comment by andrelandgraf** [comment]
Hi @sajidfrommerqata, is there a specific reason why you are setting the value prop? 

Please find the description of property [value in the README](https://github.com/andrelandgraf/react-datalist-input#markdown-header-value). You should only set value if you have a very specific use case. Try without using the value prop and it should work fine. 

If you require the value prop, e.g. because you want to alter the value in the input field the user is seeing or clear it on your own demands, than you also need to implement [onInput](https://github.com/andrelandgraf/react-datalist-input#markdown-header-onInput) to update value. If you do so, you are responsible for the value lifecycle and need to alter value based on onClick and onSelect and so on. Again, that's mostly for edge cases.

Hope that helps!

**Comment by sajidfrommerqata** [comment]
Thanks onInput worked
